apiVersion: v1
kind: Secret
metadata:
  name: sre-decision-api-secret
  namespace: sre-decision-intelligence
  labels:
    app.kubernetes.io/name: sre-decision-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: sre-decision-intelligence-platform
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://sre:sre_password@sre-decision-postgres:5432/sre_decision_intelligence
