apiVersion: v1
kind: Service
metadata:
  name: sre-decision-api
  namespace: sre-decision-intelligence
  labels:
    app.kubernetes.io/name: sre-decision-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: sre-decision-intelligence-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sre-decision-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
