apiVersion: v1
kind: ResourceQuota
metadata:
  name: sre-decision-namespace-quota
  namespace: sre-decision-intelligence
  labels:
    app.kubernetes.io/name: sre-decision-security-baseline
    app.kubernetes.io/component: runtime-security
    app.kubernetes.io/part-of: sre-decision-intelligence-platform
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    persistentvolumeclaims: "5"
