from typing import Any

from app.signals.models import NormalizedSignal, SignalDomain, SignalSource
from app.signals.normalizer import (
    make_signal,
    severity_from_availability,
    severity_from_boolean_health,
    severity_from_endpoints,
    severity_from_probe_success,
)


def normalize_frontend_availability_signals(
    raw_signals: dict[str, Any],
    service: str = "frontend",
    namespace: str = "fintech-workload",
) -> list[NormalizedSignal]:
    return [
        make_signal(
            name="probe_success",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.PROMETHEUS,
            service=service,
            namespace=namespace,
            value=raw_signals.get("probe_success"),
            unit="boolean",
            severity=severity_from_probe_success(raw_signals.get("probe_success")),
            meaning="Frontend synthetic probe success state",
            raw={"query_result": raw_signals.get("probe_success")},
        ),
        make_signal(
            name="frontend_availability_5m",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.PROMETHEUS,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_availability_5m"),
            unit="ratio",
            severity=severity_from_availability(raw_signals.get("frontend_availability_5m")),
            meaning="Frontend availability over the last 5 minutes",
            raw={"query_result": raw_signals.get("frontend_availability_5m")},
        ),
        make_signal(
            name="alert_state",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.PROMETHEUS,
            service=service,
            namespace=namespace,
            value=raw_signals.get("alert_state"),
            unit="state",
            meaning="Prometheus alert state for frontend availability SLO",
            raw={"query_result": raw_signals.get("alert_state")},
        ),
        make_signal(
            name="frontend_endpoints",
            domain=SignalDomain.PLATFORM,
            source=SignalSource.KUBERNETES,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_endpoints"),
            unit="endpoint-list",
            severity=severity_from_endpoints(raw_signals.get("frontend_endpoints")),
            meaning="Kubernetes Service backend endpoints for frontend",
            raw={"kubernetes_value": raw_signals.get("frontend_endpoints")},
        ),
        make_signal(
            name="frontend_pod_ready",
            domain=SignalDomain.PLATFORM,
            source=SignalSource.KUBERNETES,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_pod_ready"),
            unit="boolean",
            severity=severity_from_boolean_health(raw_signals.get("frontend_pod_ready")),
            meaning="Frontend pod readiness state",
            raw={"kubernetes_value": raw_signals.get("frontend_pod_ready")},
        ),
        make_signal(
            name="frontend_pod_status",
            domain=SignalDomain.PLATFORM,
            source=SignalSource.KUBERNETES,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_pod_status"),
            unit="status",
            meaning="Frontend pod status summary",
            raw={"kubernetes_value": raw_signals.get("frontend_pod_status")},
        ),
        make_signal(
            name="frontend_logs",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.OPENSEARCH,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_logs"),
            unit="summary",
            meaning="Frontend application log error summary",
            raw={"opensearch_value": raw_signals.get("frontend_logs")},
        ),
        make_signal(
            name="frontend_error_log_count",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.OPENSEARCH,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_error_log_count"),
            unit="count",
            meaning="Frontend error log count from OpenSearch",
            raw={"opensearch_value": raw_signals.get("frontend_error_log_count")},
        ),
        make_signal(
            name="frontend_5xx_rate",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.PROMETHEUS,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_5xx_rate"),
            unit="ratio",
            meaning="Frontend 5xx error rate",
            raw={"query_result": raw_signals.get("frontend_5xx_rate")},
        ),
        make_signal(
            name="frontend_latency_p95_ms",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.PROMETHEUS,
            service=service,
            namespace=namespace,
            value=raw_signals.get("frontend_latency_p95_ms"),
            unit="milliseconds",
            meaning="Frontend p95 latency in milliseconds",
            raw={"query_result": raw_signals.get("frontend_latency_p95_ms")},
        ),
        make_signal(
            name="transaction_error_rate",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.PROMETHEUS,
            service="transaction",
            namespace=namespace,
            value=raw_signals.get("transaction_error_rate"),
            unit="ratio",
            meaning="Transaction error rate",
            raw={"query_result": raw_signals.get("transaction_error_rate")},
        ),
        make_signal(
            name="backend_timeout_count",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.OPENSEARCH,
            service=None,
            namespace=namespace,
            value=raw_signals.get("backend_timeout_count"),
            unit="count",
            meaning="Backend timeout count from application logs",
            raw={"opensearch_value": raw_signals.get("backend_timeout_count")},
        ),
        make_signal(
            name="ledger_database_error_count",
            domain=SignalDomain.WORKLOAD,
            source=SignalSource.OPENSEARCH,
            service="ledger",
            namespace=namespace,
            value=raw_signals.get("ledger_database_error_count"),
            unit="count",
            meaning="Ledger/database error count from application logs",
            raw={"opensearch_value": raw_signals.get("ledger_database_error_count")},
        ),
    ]
