apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        forward . 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 {
           max_concurrent 1000
        }


        # forward . /etc/resolv.conf {
        #   max_concurrent 1000
        # }

        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-05T22:42:02Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "19354067"
  uid: a4b7966d-6012-47a6-ba08-124170a3dfca
